In [1]:
from map_utils import *
from LoadLSeg import *
import torchvision.transforms as transforms
from test_lseg_zs import *

/home/fyp/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Namespace(model='encnet', backbone='clip_vitl16_384', dataset='fss', workers=16, base_size=520, crop_size=480, train_split='train', aux=False, se_loss=False, se_weight=0.2, batch_size=16, test_batch_size=16, no_cuda=False, seed=1, weights='/home/fyp/lang-seg/checkpoints/demo_e200.ckpt', eval=False, acc_bn=False, test_val=False, no_val=False, module='clipseg_DPT_test_v2', scale_inv=False, widehead=True, widehead_hr=False, ignore_index=255, jobname='default', strict=True, use_pretrained='True', arch_option=0, nshot=0, fold=0, nworker=0, bsz=1, benchmark='pascal', datapath='data/Datasets_HSN', activation='relu', cuda=True)
Loading model...


/home/fyp/.local/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/migration.py:208: You have multiple `ModelCheckpoint` callback states in this checkpoint, but we found state keys that would end up colliding with each other after an upgrade, which means we can't differentiate which of your checkpoint callbacks needs which states. At least one of your `ModelCheckpoint` callbacks will not be able to reload the state.
Lightning automatically upgraded your loaded checkpoint from v1.3.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint checkpoints/demo_e200.ckpt`
/home/fyp/lang-seg/modules/lsegmentation_module_zs.py:50: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = amp.GradScaler(enabled=self.enabled)

:=========== Few-shot Seg. with HSNet ===========
|             datapath: data/Datasets_HSN       
|       

use norm: [0.5, 0.5, 0.5], [0.5, 0.5, 0.5]
['ac_wall', 'acorn', 'adhensive_tape', 'adidas_logo1', 'adidas_logo2', 'afghan_hound', 'african_elephant', 'african_grey', 'agama', 'air_strip', 'aircraft_carrier', 'airedale', 'airship', 'almond', 'ambulance', 'american_staffordshire', 'anemone_fish', 'angora', 'apple', 'armour', 'ashtray', 'assult_rifle', 'aubergine', 'avocado', 'baboon', 'backpack', 'bagel', 'balance_weight', 'bald_eagle', 'ballpoint', 'banana', 'band-aid', 'banded_gecko', 'barometer', 'baseball_bat', 'baseball_player', 'basketball', 'bassoon', 'bathtub', 'battery', 'beacon', 'beaker', 'beam_bridge', 'bear', 'beaver', 'bedlington_terrier', 'bee_house', 'besom', 'birdhouse', 'bison', 'black_grouse', 'black_stork', 'black_swan', 'blossom_card', 'boa_constrictor', 'bolotie', 'bomb', 'border_terrier', 'boston_bull', 'bottle_cap', 'bouzouki', 'box_turtle', 'bra', 'bracelet', 'bradypod', 'brain_coral', 'brambling', 'brasscica', 'brick', 'brick_card', 'brick_tea', 'briefcase', 'br

In [3]:
import pickle
path = '/home/fyp/llmbot2_ws/src/sem_map/sem_map/'
with open(path+"pcfm.pkl", "rb") as f:
    pcfm = pickle.load(f)   

In [ ]:
text = "box"
with torch.no_grad():
    text_feat = model.encode_text(text)
similarities = []
keys = list(pcfm.keys())
values = list(pcfm.values())
for val in values:
    similarities.append(val.half() @ text_feat.t())
similarities = torch.cat(similarities)
similarities = similarities.cpu().detach().numpy()
print(similarities)
print(np.argmax(similarities))


[0.751  0.8916 0.8374 0.871  0.8667 0.764  0.806  0.7495 0.885  0.757
 0.786  0.7373 0.884  0.7573 0.8174 0.835  0.7725 0.786  0.804  0.8237
 0.8174 0.8003 0.7393 0.7236 0.7896 0.8003 0.8726 0.81   0.7544 0.854
 0.7656 0.753  0.848  0.7954 0.869  0.7495 0.8916 0.8506 0.8735 0.7695
 0.776  0.72   0.756  0.834  0.8394 0.7573 0.8643 0.7896 0.728  0.75
 0.7393 0.7563 0.7373 0.8643 0.82   0.831  0.896  0.7583 0.738  0.82
 0.7646 0.754  0.7373 0.7393 0.7524 0.772  0.766  0.7397 0.785  0.7554
 0.8486 0.741  0.867  0.829  0.878  0.8657 0.7896 0.7695 0.755  0.722
 0.7417 0.8916 0.802  0.883  0.831  0.7793 0.8853 0.806  0.821  0.791
 0.884  0.7993 0.751  0.752  0.7725 0.8745 0.8013 0.7993 0.85   0.8545
 0.849  0.8027 0.834  0.806  0.751  0.8784 0.8037 0.8306 0.7964 0.8906
 0.7905 0.805  0.7495 0.7427 0.817  0.783  0.8394 0.83   0.8853 0.811
 0.792  0.7837 0.874  0.746  0.758  0.7886 0.8228 0.8184 0.8745 0.746
 0.878  0.8276 0.8267 0.8643 0.8125 0.7544 0.756  0.881  0.783  0.839
 0.7837 0.83   0.

In [22]:
idx = np.where(similarities>0.89)[0]

array([  1,  36,  56,  81, 109, 160, 163, 172, 199, 206, 221, 225, 230,
       279, 283, 348, 630, 642, 649, 650, 726, 730, 762, 801, 804])

In [32]:
points = np.array(list(pcfm.keys()))[idx]

In [33]:
print(points)

[[ 1.8  1.2 -0.8]
 [ 1.8  0.  -1.2]
 [ 1.2  1.  -0.6]
 [ 2.6  1.  -1. ]
 [ 1.8  0.8 -1.2]
 [ 1.2 -0.4 -0.6]
 [ 2.2 -0.4 -0.8]
 [ 1.8  0.  -1. ]
 [ 2.  -0.2 -0.8]
 [ 2.2  0.8 -1.4]
 [ 1.4  0.  -1. ]
 [ 0.4 -0.2 -0.2]
 [ 0.6 -0.2 -0.4]
 [ 1.4 -0.4 -0.6]
 [ 3.2  0.8 -1.8]
 [ 1.8  1.4 -1. ]
 [ 2.  -0.4 -0.8]
 [ 1.8 -0.6 -1.2]
 [ 2.2 -0.8 -0.8]
 [ 2.  -0.6 -1.2]
 [ 2.6  1.8 -1.4]
 [ 2.8  2.2 -1.6]
 [ 2.4  2.  -1.4]
 [ 1.6 -0.2 -1. ]
 [ 1.8 -0.2 -1.2]]
